export const ROLE = {
  ADMIN: "ADMIN",
  SELLER: "SELLER",
  USER:"USER"
  
}

export const VISIBILITY = {
  PUBLIC : 'PUBLIC',
  FOLLOWERS : 'FOLLOWERS',
  FRIENDS : 'FRIENDS',
  ONLY_ME : 'ONLY_ME',
}

export const FRIEND_REQUEST_STATUS = {
  PENDING : 'PENDING',
  ACCEPTED : 'ACCEPTED',
  CANCELLED : 'CANCELLED',
}