export const ROLE = {
  ADMIN: "ADMIN",
  SELLER: "SELLER",
  USER:"USER"
  
}

export const VISIBILITY = {
  PUBLIC : 'PUBLIC',
  FOLLOWERS : 'FOLLOWERS',
  FRIENDS : 'FRIENDS',
  ONLY_ME : 'ONLY_ME',
}

export const FRIEND_REQUEST_STATUS = {
  PENDING : 'PENDING',
  ACCEPTED : 'ACCEPTED',
  CANCELLED : 'CANCELLED',
}

export enum ReactType {
  LIKE = 'LIKE',
  LOVE = 'LOVE',
  MOTIVATED = 'MOTIVATED',
  HAHA = 'HAHA',
  QUESTION = 'QUESTION',
  SAD = 'SAD',
  AGREE = 'AGREE',
  ANGRY = 'ANGRY',
  HELPFUL = 'HELPFUL',
  THANKS = 'THANKS',
}
